version: "3.7"

services:
  db:
    image: mysql:8.0.23
    container_name: blitz-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal-site-db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  data:
